### ISSUE TITLE
MissingPlatformDirectoryException on Arch

### ISSUE THREAD

**Issue by 3isenHeiM** [ente/ente#2046]
### Description

I've installed `ente-auth-bin` from the AUR repos, and I'm getting this error :+1: 
```
flutter:  [ente_logging] [INFO] [2024-06-07 09:37:42.036690] log file for today: File: '/home/$USERR/.local/share/io.ente.auth/logs/2024-6-7.txt' with prefix 
flutter: [ente_logging] [INFO] [2024-06-07 09:37:42.036690] app version: '3.0.8+308'
flutter: [ente_logging] [INFO] [2024-06-07 09:37:42.036690] 
flutter:  [main] [INFO] [2024-06-07 09:37:42.036727] Starting app in foreground
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPlatformDirectoryException(Unable to get application documents directory)
#0      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:123)
<asynchronous suspension>
#1      Configuration.init (package:ente_auth/core/configuration.dart:77)
<asynchronous suspension>
#2      _init (package:ente_auth/main.dart:150)
<asynchronous suspension>
#3      _runInForeground.<anonymous closure> (package:ente_auth/main.dart:93)
<asynchronous suspension>
#4      SuperLogging.main (package:ente_auth/core/logging/super_logging.dart:201)
<asynchronous suspension>
#5      _runWithLogs (package:ente_auth/main.dart:122)
<asynchronous suspension>
#6      _runInForeground (package:ente_auth/main.dart:91)
<asynchronous suspension>
#7      main (package:ente_auth/main.dart:82)
<asynchronous suspension>
```

The Application window opens, but hangs and stays empty.

Where can this come from, and how can I solve it ? 

### Version

3.0.8-1

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by LRitzdorf** [comment]
I've just installed the same package on my Arch system, and it works as expected. Given that error message, I suspect that you might not have a configured "Documents" directory (via the [XDG User Directories system](https://wiki.archlinux.org/title/XDG_user_directories#Creating_default_directories)).
To test that, try running `xdg-user-dir DOCUMENTS`, which should return your user's documents folder.

**Comment by 3isenHeiM** [comment]
I had to install this package (`xdg-user-dirs`), but then I had a `PlatformException(Libsecret error, Failed to unlock the keyring, null, null)` error.

This issue https://github.com/ente-io/ente/discussions/1423 helped me, I was missing the `gnome-keyring` package.
Could these 2 packages maybe be set as dependencies ?

Thanks for the help !

**Comment by AmanRajSinghMourya** [comment]
Hey @3isenHeiM, thanks for reporting this. The MissingPlatformDirectoryException seen in Ente Auth v3.0.8 was addressed by #3334 (https://github.com/ente/ente/pull/3334), which moved the Linux app data and database paths to XDG directories. The change shipped in v4.1.0 (https://github.com/ente/ente/releases/tag/auth-v4.1.0).

The current ente-auth-bin AUR package also declares xdg-user-dirs and an org.freedesktop.secrets provider, covering the dependencies missing from the old 3.0.8 package.

We’re closing this as resolved. If the same exception still occurs on the latest version, please share the full terminal output, distro, desktop and installation package, and we can reopen it.
